### ISSUE TITLE
A circular dependency was detected for the service of type 'Microsoft.Maui.IApplication'

### ISSUE THREAD

**Issue by gvhung** [MPowerKit/Navigation#1]
Edit App.xaml.cs the same below:

`using MPowerKit.Navigation.Interfaces;

namespace Sample;

public partial class App : Application
{
    private readonly INavigationService _navigationService = null;

    public App(INavigationService navigationService)
    {
        _navigationService = navigationService;
        InitializeComponent();
    }
}`

-----------------------------------

System.InvalidOperationException: 'A circular dependency was detected for the service of type 'Microsoft.Maui.IApplication'.
Microsoft.Maui.IApplication(Sample.App) -> MPowerKit.Navigation.Interfaces.INavigationService(MPowerKit.Navigation.NavigationService) -> MPowerKit.Navigation.Interfaces.IWindowManager(MPowerKit.Navigation.WindowInfrastructure.MPowerKitWindowManager) -> Microsoft.Maui.IApplication'

**Comment by Alex-Dobrynin** [comment]
Why do you need INavigationService inside the App class?

**Comment by gvhung** [comment]
I do not use OnAppStart action in UseMPowerKitNavigation. I need INavigationService in App class.

**Comment by Alex-Dobrynin** [comment]
You cannot use it like this, only through OnAppStart

**Comment by gvhung** [comment]
Thanks a lot. I will try OnAppStart
