### ISSUE TITLE
can't find the csproj named 'MPowerKit.Popups.csproj"'

### ISSUE THREAD

**Issue by mzy666888** [MPowerKit/Navigation#3]
I can't find the csproj named `MPowerKit.Popups.csproj` at `MPowerKit.Navigation.Popups`

**Comment by Alex-Dobrynin** [comment]
You need to download another repository MPowerKit.Popups from here https://github.com/MPowerKit/Popups for this purpose and put these two repos into one folder
<img width="219" alt="image" src="https://github.com/user-attachments/assets/a0df50f9-b9aa-4b50-afaa-32df05501fc8">

**Comment by mzy666888** [comment]
thanks!
