### ISSUE TITLE
Registering IView and IViewModel?

### ISSUE THREAD

**Issue by kerberosargos** [MPowerKit/Navigation#4]
Hello is there any way to register as following prism sample;

`ViewModelLocationProvider.Register<OverlayMenuPart, OverlayMenuPartialViewModel>();`

OverlayMenuPart is **ContentView** and OverlayMenuPartialViewModel is **ViewModel**.

I mean I would like to AutoWire register for those type.

Thank you in adavnce.

**Comment by Alex-Dobrynin** [comment]
Hi. you can register views and viewmodels via IServiceCollection: `serviceCollection.RegisterForNavigation<View, ViewModel>();`, but this will work only with regions or with regular navigation.
If you want something like in PRISM attached property to your view `prism:ViewModelLocator.AutoWireViewModel="True"`, then this is not implemented here, and probably will not.
For me, there is no sense to autowire your custom view with some viewmodel, if this view is not taking part in navigation and just being regular view in your page.

But, if you lack some functionality, you always may propose a PR.

**Comment by kerberosargos** [comment]
Thank you for your interest. I think I will achieve by using regions.
